### ISSUE TITLE
有关微调其他数据集的疑问

### ISSUE THREAD

**Issue by Xie-Muxi** [hitachinsk/SAMed#17]
作者你好，我最近想尝试使用遥感数据集（主要还是三个通道的，如果可能的话，后面可能还会测试多光谱，，但是考虑到SAM的训练数据是自然图像，更多通道输入效果应该不会很理想）微调SAM，我预期计划是先跑通SAM，然后再增加插件的调试

我注意到SAMed的做法是在SAM的基础上修改num_multimask_outputs参数为num_classes, 我按照同样的做法在（https://github.com/luca-medeiros/lightning-sam）上修改SAM源码增加num_classes参数，但是没有增加LoRa层，但在计算IoU的时候出现与mask维度不匹配的情况（无论num_classes的值是多少），调试了挺久的也没有解决。

所以想跟您请教一些问题
1.您没有直接将num_classes用于修改最后的输出层的原因是？
2. 为了限制输出的分割类别，我目前想到的方法除了增加num_classes参数之外，修改loss应该也可以，您是否可以针对这个问题提供一些建议？
3. 直接使用遥感数据集微调LoRA_SAM 的话，除了写DataLoader之外，是否有其他地方需要注意修改？

非常感谢🙏

**Comment by yao-yu1999** [comment]
> 作者你好，我最近想尝试使用遥感数据集（主要还是三个通道的，如果可能的话，后面可能还会测试多光谱，，但是考虑到SAM的训练数据是自然图像，更多通道输入效果应该不会很理想）微调SAM，我预期计划是先跑通SAM，然后再增加插件的调试
> 
> 我注意到SAMed的做法是在SAM的基础上修改num_multimask_outputs参数为num_classes, 我按照同样的做法在（[https://github.com/luca-medeiros/lightning-sam）上修改SAM源码增加num_classes参数，但是没有增加LoRa层，但在计算IoU的时候出现与mask维度不匹配的情况（无论num_classes的值是多少），调试了挺久的也没有解决。](https://github.com/luca-medeiros/lightning-sam%EF%BC%89%E4%B8%8A%E4%BF%AE%E6%94%B9SAM%E6%BA%90%E7%A0%81%E5%A2%9E%E5%8A%A0num_classes%E5%8F%82%E6%95%B0%EF%BC%8C%E4%BD%86%E6%98%AF%E6%B2%A1%E6%9C%89%E5%A2%9E%E5%8A%A0LoRa%E5%B1%82%EF%BC%8C%E4%BD%86%E5%9C%A8%E8%AE%A1%E7%AE%97IoU%E7%9A%84%E6%97%B6%E5%80%99%E5%87%BA%E7%8E%B0%E4%B8%8Emask%E7%BB%B4%E5%BA%A6%E4%B8%8D%E5%8C%B9%E9%85%8D%E7%9A%84%E6%83%85%E5%86%B5%EF%BC%88%E6%97%A0%E8%AE%BAnum_classes%E7%9A%84%E5%80%BC%E6%98%AF%E5%A4%9A%E5%B0%91%EF%BC%89%EF%BC%8C%E8%B0%83%E8%AF%95%E4%BA%86%E6%8C%BA%E4%B9%85%E7%9A%84%E4%B9%9F%E6%B2%A1%E6%9C%89%E8%A7%A3%E5%86%B3%E3%80%82)
> 
> 所以想跟您请教一些问题 1.您没有直接将num_classes用于修改最后的输出层的原因是？ 2. 为了限制输出的分割类别，我目前想到的方法除了增加num_classes参数之外，修改loss应该也可以，您是否可以针对这个问题提供一些建议？ 3. 直接使用遥感数据集微调LoRA_SAM 的话，除了写DataLoader之外，是否有其他地方需要注意修改？
> 
> 非常感谢🙏

你好，我也在研究这个，可以交流一下吗？

**Comment by Xie-Muxi** [comment]
> > 作者你好，我最近想尝试使用遥感数据集（主要还是三个通道的，如果可能的话，后面可能还会测试多光谱，，但是考虑到SAM的训练数据是自然图像，更多通道输入效果应该不会很理想）微调SAM，我预期计划是先跑通SAM，然后再增加插件的调试
> > 我注意到SAMed的做法是在SAM的基础上修改num_multimask_outputs参数为num_classes, 我按照同样的做法在（[https://github.com/luca-medeiros/lightning-sam）上修改SAM源码增加num_classes参数，但是没有增加LoRa层，但在计算IoU的时候出现与mask维度不匹配的情况（无论num_classes的值是多少），调试了挺久的也没有解决。](https://github.com/luca-medeiros/lightning-sam%EF%BC%89%E4%B8%8A%E4%BF%AE%E6%94%B9SAM%E6%BA%90%E7%A0%81%E5%A2%9E%E5%8A%A0num_classes%E5%8F%82%E6%95%B0%EF%BC%8C%E4%BD%86%E6%98%AF%E6%B2%A1%E6%9C%89%E5%A2%9E%E5%8A%A0LoRa%E5%B1%82%EF%BC%8C%E4%BD%86%E5%9C%A8%E8%AE%A1%E7%AE%97IoU%E7%9A%84%E6%97%B6%E5%80%99%E5%87%BA%E7%8E%B0%E4%B8%8Emask%E7%BB%B4%E5%BA%A6%E4%B8%8D%E5%8C%B9%E9%85%8D%E7%9A%84%E6%83%85%E5%86%B5%EF%BC%88%E6%97%A0%E8%AE%BAnum_classes%E7%9A%84%E5%80%BC%E6%98%AF%E5%A4%9A%E5%B0%91%EF%BC%89%EF%BC%8C%E8%B0%83%E8%AF%95%E4%BA%86%E6%8C%BA%E4%B9%85%E7%9A%84%E4%B9%9F%E6%B2%A1%E6%9C%89%E8%A7%A3%E5%86%B3%E3%80%82)
> > 所以想跟您请教一些问题 1.您没有直接将num_classes用于修改最后的输出层的原因是？ 2. 为了限制输出的分割类别，我目前想到的方法除了增加num_classes参数之外，修改loss应该也可以，您是否可以针对这个问题提供一些建议？ 3. 直接使用遥感数据集微调LoRA_SAM 的话，除了写DataLoader之外，是否有其他地方需要注意修改？
> > 非常感谢🙏
> 
> 你好，我也在研究这个，可以交流一下吗？

可以的，您留个联系方式？

**Comment by yao-yu1999** [comment]
谢谢你！我的微信是18672091675




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hitachinsk/SAMed"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hitachinsk/SAMed] 有关微调其他数据集的疑问 (Issue #17)





   
作者你好，我最近想尝试使用遥感数据集（主要还是三个通道的，如果可能的话，后面可能还会测试多光谱，，但是考虑到SAM的训练数据是自然图像，更多通道输入效果应该不会很理想）微调SAM，我预期计划是先跑通SAM，然后再增加插件的调试
 我注意到SAMed的做法是在SAM的基础上修改num_multimask_outputs参数为num_classes, 我按照同样的做法在（https://github.com/luca-medeiros/lightning-sam）上修改SAM源码增加num_classes参数，但是没有增加LoRa层，但在计算IoU的时候出现与mask维度不匹配的情况（无论num_classes的值是多少），调试了挺久的也没有解决。
 所以想跟您请教一些问题 1.您没有直接将num_classes用于修改最后的输出层的原因是？ 2. 为了限制输出的分割类别，我目前想到的方法除了增加num_classes参数之外，修改loss应该也可以，您是否可以针对这个问题提供一些建议？ 3. 直接使用遥感数据集微调LoRA_SAM 的话，除了写DataLoader之外，是否有其他地方需要注意修改？
 非常感谢🙏
  
你好，我也在研究这个，可以交流一下吗？
  
可以的，您留个联系方式？

**Comment by hitachinsk** [comment]
第一个问题：num_classes主要是为了使得输出的channel数量与segmentation类别匹配
至于第二个和第三个问题，我对遥感图像还比较陌生，我没有做过遥感图像，所以很抱歉我不能提供有效的建议。
