### ISSUE TITLE
 A question about the calculation of test metrics

### ISSUE THREAD

**Issue by Magic-lem** [hitachinsk/SAMed#29]
Hello! Thank you very much for your work. I have a question while reading the code: why does the code return a Dice coefficient of 1 when there are pixels of that class in the predicted mask but not in the ground truth?

The code is as follows:

`elif pred.sum() > 0 and gt.sum() == 0:
    return 1, 0`

I'm looking forward to your answer, and I really appreciate it!

**Comment by hitachinsk** [comment]
The test metrics are borrowed from transunet, which measure the metrics in the 3D space but not in the image space. Such situation may not likely to happen when we test the metrics in the 3D space.

**Comment by Magic-lem** [comment]
Got it, thank you for your answer.
